version: "3.8"

services:
  fastapi-app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - fastapi_code:/app   # writable volume for running code
      - .:/source:ro               # original source read-only
    ports:
      - "9000:8000"

  jupyter:
    build: .
    volumes:
      - fastapi_code:/app   # same writable volume
      - .:/source:ro               # original source read-only
    ports:
      - "8889:8888"
    stdin_open: true
    tty: true
    working_dir: /app
    command: >
      jupyter lab
      --ip=0.0.0.0
      --port=8888
      --allow-root
      --no-browser

volumes:
  fastapi_code:
